# Generated by Django 4.2.17 on 2025-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
